spring:
  liquibase:
    enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5440/stocks
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB
